"""Result tables (Markdown) from the committed result files; it only reads results.

python scripts/make_tables.py            # experiments/results -> docs/results.md

The table builder refuses QUICK rows and oracle rows without their ORACLE marker; strategy
tables keep the order of the registry. Every table is a simulation result.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))

from dynamic_trading_engine.experiments.tables import markdown  # noqa: E402


def read(res, name):
    with open(os.path.join(res, name), encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def pm(r, k, nd=4):
    try:
        return f"{float(r[k + '_mean']):.{nd}f} ± {float(r[k + '_ci95']):.{nd}f}"
    except (KeyError, ValueError):
        return "n/a"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=os.path.join("experiments", "results"))
    ap.add_argument("--out", default=os.path.join("docs", "results.md"))
    a = ap.parse_args(argv)
    res = a.results
    with open(os.path.join(res, "manifest.json"), encoding="utf-8") as fh:
        man = json.load(fh)
    out = [
        "# Results (simulated)",
        "",
        "Generated by `scripts/make_tables.py` from the committed files in `experiments/results/`. "
        "Every number is a simulation result on the synthetic market of `docs/data.md`, under the assumptions "
        "stated there and in `docs/protocol.md`; it says nothing about real markets. "
        f"Evaluation commit `{man['git']['commit'][:12]}` (tree clean: {not man['git']['dirty']}), "
        f"{man['n_loop_runs']} loop runs, {man['workers']} workers, CPU {man['hardware']['cpu']}.",
        "",
    ]
    s2 = read(res, "s2_summary.csv")
    pairs = {(r["strategy"], r["baseline"]): r for r in read(res, "s2_paired.csv")}
    glance = []
    for r in s2:
        g = {
            "strategy": r["strategy"],
            "label": r["label"],
            "ce": pm(r, "ce_ann"),
            "sharpe": r["sharpe"],
            "gross": r["gross_exposure"],
            "flat": r["flat_frac"],
        }
        for b in ("EW", "RANK_LS"):
            p = pairs.get((r["strategy"], b))
            g[b] = (
                f"{float(p['diff_mean']):+.4f} ± {float(p['diff_ci']):.4f} ({p['wins']}/{p['ties']}/{p['losses']})"
                if p
                else "-"
            )
        glance.append(g)
    out += [
        "## S2 at a glance (the table of the README)",
        "",
        markdown(
            glance,
            [
                ("strategy", "strategy"),
                ("ce", "ce_ann (95% CI)"),
                ("EW", "vs EW (W/T/L)"),
                ("RANK_LS", "vs RANK_LS (W/T/L)"),
                ("sharpe", "Sharpe"),
                ("gross", "gross exp."),
                ("flat", "flat bars"),
            ],
            nd=2,
        ),
        "",
    ]
    for r in s2:
        r["ce"] = pm(r, "ce_ann")
    out += [
        "## S2 main comparison (base market, 30 seeds, tuned with 16 trials each on seeds 100-103)",
        "",
        markdown(
            s2,
            [
                ("strategy", "strategy"),
                ("label", "label"),
                ("ce", "ce_ann (95% CI)"),
                ("sharpe", "Sharpe"),
                ("sharpe_gross", "gross Sharpe"),
                ("ann_return", "ann. return"),
                ("ann_vol", "ann. vol"),
                ("max_drawdown", "max DD"),
                ("cvar95", "CVaR95"),
                ("turnover", "turnover/bar"),
                ("cost_drag", "cost drag/yr"),
                ("gross_exposure", "gross exp."),
                ("flat_frac", "flat bars"),
                ("hold_frac", "held decisions"),
            ],
        ),
        "",
    ]
    pair = read(res, "s2_paired.csv")
    for r in pair:
        r["d"] = f"{float(r['diff_mean']):.4f} ± {float(r['diff_ci']):.4f}"
        r["wtl"] = f"{r['wins']}/{r['ties']}/{r['losses']}"
    out += [
        "Paired differences of ce_ann (strategy minus baseline, same seed; 95% CI; wins/ties/losses):",
        "",
        markdown(
            pair,
            [
                ("strategy", "strategy"),
                ("baseline", "baseline"),
                ("d", "difference"),
                ("wtl", "W/T/L"),
            ],
        ),
        "",
    ]
    dsr = read(res, "s2_dsr.csv")
    share = sum(1 for r in dsr if r["dsr_gt_0.95"] == "true") / len(dsr)
    sel = {}
    for r in dsr:
        sel[r["selected_by_sharpe"]] = sel.get(r["selected_by_sharpe"], 0) + 1
    out += [
        f"Deflated Sharpe ratio (N = 8 strategies per seed, the highest per-bar Sharpe selected): DSR > 0.95 on "
        f"{share:.0%} of {len(dsr)} seeds; selected by Sharpe: "
        + ", ".join(f"{k} {v}" for k, v in sorted(sel.items()))
        + ".",
        "",
    ]
    lad = read(res, "s2b_ladder.csv")
    for r in lad:
        r["ce"] = pm(r, "ce_ann")
        r["q"] = f"{float(r['forecast_quality']):.3f}"
    out += [
        "## S2b information ladder (MV; gamma re-tuned per rung on an 8-value grid; bounds)",
        "",
        markdown(
            lad,
            [
                ("variant", "rung"),
                ("label", "label"),
                ("q", "corr with m"),
                ("ce", "ce_ann (95% CI)"),
                ("turnover", "turnover/bar"),
                ("cost_drag", "cost drag/yr"),
            ],
        ),
        "",
    ]
    s3 = read(res, "s3.csv")
    for r in s3:
        r["ce"] = pm(r, "ce_ann")
        if r.get("diff_vs_parity"):
            r["d"] = f"{float(r['diff_vs_parity']):.4f} ± {float(r['diff_ci95']):.4f}"
            r["wtl"] = f"{r['wins']}/{r['ties']}/{r['losses']}"
    out += [
        "## S3 constraints, costs, schedule (tuned MV at the parity setting, 20 seeds)",
        "",
        markdown(
            s3,
            [
                ("variant", "variant"),
                ("ce", "ce_ann (95% CI)"),
                ("d", "vs parity"),
                ("wtl", "W/T/L"),
                ("turnover", "turnover/bar"),
                ("cost_drag", "cost drag/yr"),
                ("gross_exposure", "gross exp."),
            ],
        ),
        "",
    ]
    s4 = read(res, "s4.csv")
    for r in s4:
        if r["variant"].split("|")[-1] == "sample":
            r["share_below_sample"] = "n/a"  # the model is the reference itself (rounding only)
        r["variant"] = r["variant"].replace("|", " / ")
    for r in s4:
        r["vol"] = (
            f"{float(r['ann_vol_mean'] if 'ann_vol_mean' in r else r['ann_vol']):.4f} ± {float(r['ann_vol_ci95']):.4f}"
        )
    out += [
        "## S4 risk models (MINVAR, 20 seeds; declared quantity: realized volatility, lower is better)",
        "",
        markdown(
            s4,
            [
                ("variant", "market / window / model"),
                ("n_over_W", "n/W"),
                ("vol", "realized ann. vol (95% CI)"),
                ("frobenius_rel", "rel. Frobenius error"),
                ("calibration", "realized/predicted vol"),
                ("share_below_sample", "share below sample"),
            ],
        ),
        "",
        '"share below sample" is the share of decisions at which the model\'s relative Frobenius error '
        "(against the true covariance of the next bar) is below that of the plain sample covariance of the "
        "same window of returns; for the `sample` model the two are the same matrix up to the eigenvalue floor "
        "and rounding, so the share only measures on which side the rounding noise falls and is shown as n/a.",
        "",
    ]
    s5 = read(res, "s5_shift.csv")
    for r in s5:
        for ref in ("EW", "MV"):
            if r.get(f"post_diff_vs_{ref}"):
                r[f"pd_{ref}"] = (
                    f"{float(r[f'post_diff_vs_{ref}']):.4f} ± {float(r[f'post_diff_vs_{ref}_ci95']):.4f}"
                    f" ({r[f'post_wtl_vs_{ref}']})"
                )
        for k in ("effect", "after_minus_before", "ce_post_shift"):
            if r.get(f"{k}_mean"):
                r[k] = pm(r, k)
    out += [
        "## S5 distribution shift (shift market, 30 seeds; RETUNED rows are bounds)",
        "",
        markdown(
            s5,
            [
                ("strategy", "strategy"),
                ("label", "label"),
                ("effect", "effect of the shift (paired)"),
                ("after_minus_before", "after - before (shift run)"),
                ("ce_post_shift", "ce_ann after the shift"),
                ("pd_EW", "after the shift vs EW (W/T/L)"),
                ("pd_MV", "after the shift vs MV (W/T/L)"),
            ],
        ),
        "",
    ]
    s6 = read(res, "s6a_gap.csv")
    for r in s6:
        r["H"] = str(int(float(r["H"])))
        r["phi_gp"], r["Lam"] = f"{float(r['phi_gp']):g}", f"{float(r['Lam']):g}"
        r["gap"] = f"{float(r['gap_pct_mean']):.4f} ± {float(r['gap_pct_ci95']):.4f}"
    out += [
        "## S6(a) controller vs the Garleanu-Pedersen closed form (gap in % of the closed-form utility)",
        "",
        markdown(
            s6,
            [("phi_gp", "phi_gp"), ("Lam", "Lam"), ("H", "H"), ("gap", "gap % (95% CI)")],
            raw=("phi_gp", "Lam", "H"),
        ),
        "",
    ]
    s6b = read(res, "s6b_proportional.csv")
    for r in s6b:
        r["H"] = str(int(float(r["H"])))
        r["c_prop"] = f"{float(r['c_prop']):g}"
        r["gap_se"] = f"{float(r['gap_se']):.2e}"
        r["gap_pct"] = f"{float(r['gap_pct']):.4f}"
    out += [
        "## S6(b) controller vs the dynamic program, proportional cost (one seed, 50 paths, 250 steps)",
        "",
        markdown(
            s6b,
            [
                ("c_prop", "c_prop"),
                ("H", "H"),
                ("utility_dp_policy", "DP policy utility"),
                ("utility_mpc", "controller utility"),
                ("gap_pct", "gap %"),
                ("gap_se", "s.e. of difference"),
            ],
            nd=6,
            raw=("c_prop", "H", "gap_pct", "gap_se"),
        ),
        "",
    ]
    s6c = read(res, "s6c.csv")
    for r in s6c:
        r["ce"] = pm(r, "ce_ann")
        if r.get("diff_vs_H=1"):
            r["d"] = f"{float(r['diff_vs_H=1']):.4f} ± {float(r['diff_ci95']):.4f}"
            r["wtl"] = f"{r['wins']}/{r['ties']}/{r['losses']}"
    out += [
        "## S6(c) MPC horizons in the market (tuned MV configuration, delta 1; H = 1 is MV)",
        "",
        markdown(
            s6c,
            [
                ("variant", "H"),
                ("ce", "ce_ann (95% CI)"),
                ("d", "vs H=1"),
                ("wtl", "W/T/L"),
                ("turnover", "turnover/bar"),
            ],
        ),
        "",
    ]
    fr = read(res, "s7_frontier.csv")
    out += [
        "## S7(a) execution frontier, exact Almgren-Chriss world (closed form and Monte Carlo)",
        "",
        markdown(
            fr,
            [
                ("policy", "policy"),
                ("E_cf", "E (closed form)"),
                ("sd_cf", "sd (closed form)"),
                ("E_mc", "E (MC)"),
                ("E_mc_se", "MC s.e."),
                ("V_mc", "V (MC)"),
            ],
            nd=1,
        ),
        "",
    ]
    pol = read(res, "s7_policies.csv")
    for r in pol:
        r["is"] = f"{float(r['IS_bps_mean']):.2f} ± {float(r['IS_bps_ci95']):.2f}"
    out += [
        "## S7(b) policies under square-root impact, U-shaped volume, volume noise, cap 0.1",
        "",
        markdown(
            pol,
            [
                ("Q_frac_adv", "Q / ADV"),
                ("policy", "policy"),
                ("is", "IS bps (95% CI over seeds)"),
                ("IS_bps_sd_paths", "sd across paths"),
                ("completion", "completion"),
                ("slippage_vwap_bps", "vs VWAP bps"),
            ],
            nd=3,
        ),
        "",
    ]
    lc = read(res, "s7_latency_cap.csv")
    for r in lc:
        r["is"] = f"{float(r['IS_bps_mean']):.2f} ± {float(r['IS_bps_ci95']):.2f}"
    out += [
        "## S7(c) latency and participation cap (Q = 2% ADV)",
        "",
        markdown(
            lc,
            [
                ("latency", "latency"),
                ("cap", "cap"),
                ("policy", "policy"),
                ("is", "IS bps"),
                ("completion", "completion"),
            ],
            nd=3,
        ),
        "",
    ]
    de = read(res, "s7_decomposition.csv")
    out += [
        "## S7(d) shortfall decomposition (bps of Q*S0, Q = 2% ADV)",
        "",
        markdown(
            de,
            [
                ("policy", "policy"),
                ("timing_bps", "timing"),
                ("permanent_bps", "permanent"),
                ("spread_bps", "spread"),
                ("temporary_bps", "temporary"),
                ("opportunity_bps", "opportunity"),
                ("commission_bps", "commission"),
                ("IS_bps", "total"),
            ],
            nd=2,
        ),
        "",
    ]
    s8 = read(res, "s8_recost.csv")
    for r in s8:
        r["orders_per_run"] = f"{float(r['orders_per_run']):.0f}"
        for k in ("loop_cost_bps", "market_cost_bps", "twap_cost_bps", "vwap_cost_bps"):
            r[k + "_f"] = f"{float(r[k]):.2f} ± {float(r[k + '_ci95']):.2f}"
    out += [
        "## S8 post-hoc re-costing of the tuned MV's orders (execution simulator over the fill bar)",
        "",
        markdown(
            s8,
            [
                ("variant", "capital"),
                ("orders_per_run", "orders/run"),
                ("loop_cost_bps_f", "loop single print bps"),
                ("market_cost_bps_f", "market bps"),
                ("twap_cost_bps_f", "twap bps"),
                ("vwap_cost_bps_f", "vwap bps"),
                ("loop_capped_share", "loop: cap binds"),
                ("market_capped_share", "market: cap binds"),
            ],
            raw=("orders_per_run",),
        ),
        "",
    ]
    ex = read(res, "exact_references.csv")
    for r in ex:
        r["max_error"] = f"{float(r['max_error']):.2e}"
        r["n_problems"] = str(int(float(r["n_problems"])))
        r["note"] = r["note"].replace("|", "\\|")  # absolute values would split the cell
    out += [
        "## S1 exact references",
        "",
        markdown(
            ex,
            [
                ("reference", "reference"),
                ("n_problems", "n"),
                ("max_error", "max error"),
                ("statuses", "statuses"),
                ("note", "measure"),
            ],
            raw=("n_problems", "max_error"),
        ),
        "",
    ]
    sens = read(res, "sens.csv")
    for r in sens:
        r["ce"] = pm(r, "ce_ann")
    out += [
        "## SENS sensitivity",
        "",
        markdown(
            sens, [("sensitivity", "setting"), ("strategy", "strategy"), ("ce", "ce_ann (95% CI)")]
        ),
        "",
    ]
    with open(a.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
    print(a.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
