"""Tier-2 result tables (Markdown) from experiments/results/tier2; it only reads results.

python scripts/make_tables_tier2.py   # -> docs/results_tier2.md
"""

from __future__ import annotations

import csv
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))

from dynamic_trading_engine.experiments.tables import markdown  # noqa: E402

RES = os.path.join("experiments", "results", "tier2")


def read(name):
    with open(os.path.join(RES, name), encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def pmx(r, m, c, nd=4):
    try:
        return f"{float(r[m]):+.{nd}f} ± {float(r[c]):.{nd}f}"
    except (KeyError, ValueError):
        return "-"


def main() -> int:
    out = [
        "# Tier-2 results (simulated)",
        "",
        "Generated by `scripts/make_tables_tier2.py` from `experiments/results/tier2/`. Every number is a simulation "
        "result on the synthetic markets of `docs/data.md` (the fat-tail and jump variants are assumed tail models); "
        "Tier-2 strategies were tuned once with the protocol of S2 and frozen in `experiments/tuned/frozen_tier2.json` "
        "before their evaluation. Intervals: 95 percent Student-t across seeds; differences are paired on the same seeds.",
        "",
    ]
    w = read("wdro.csv")
    for r in w:
        r["ce"] = pmx(r, "ce_ann_mean", "ce_ann_ci95")
        for ref in ("CASH", "EW", "MV", "CVAR", "ROBUST"):
            r[ref] = pmx(r, f"diff_vs_{ref}", f"diff_vs_{ref}_ci95") + (
                f" ({r[f'wtl_vs_{ref}']})" if r.get(f"wtl_vs_{ref}") else ""
            )
        r["eff"] = pmx(r, "effect_of_shift_mean", "effect_of_shift_ci95")
    out += [
        "## Item 1: Wasserstein-robust mean-CVaR (WDRO; 30 seeds)",
        "",
        markdown(
            w,
            [
                ("strategy", "run"),
                ("ce", "ce_ann"),
                ("CASH", "vs CASH"),
                ("EW", "vs EW"),
                ("MV", "vs MV"),
                ("CVAR", "vs CVAR"),
                ("ROBUST", "vs ROBUST"),
                ("eff", "effect of the shift"),
            ],
        ),
        "",
    ]
    g = read("gp_aim.csv")
    for r in g:
        r["ce"] = pmx(r, "ce_ann_mean", "ce_ann_ci95")
        for ref in ("CASH", "EW", "MV", "MPC"):
            r[ref] = pmx(r, f"diff_vs_{ref}", f"diff_vs_{ref}_ci95") + (
                f" ({r[f'wtl_vs_{ref}']})" if r.get(f"wtl_vs_{ref}") else ""
            )
    out += [
        "## Item 2: multi-asset Garleanu-Pedersen rule (GP_AIM; base, 30 seeds)",
        "",
        markdown(
            g,
            [
                ("strategy", "strategy"),
                ("ce", "ce_ann"),
                ("CASH", "vs CASH"),
                ("EW", "vs EW"),
                ("MV", "vs MV"),
                ("MPC", "vs MPC"),
                ("gross_exposure", "gross exp."),
                ("turnover", "turnover/bar"),
            ],
        ),
        "",
    ]
    a = read("adaptive_execution.csv")
    for r in a:
        r["is"] = f"{float(r['IS_bps_mean']):.2f} ± {float(r['IS_bps_ci95']):.2f}"
        r["vs_static"] = pmx(r, "diff_vs_ac_static_bps", "diff_vs_ac_static_ci95", 3)
        r["vs_vwap"] = pmx(r, "diff_vs_vwap_bps", "diff_vs_vwap_ci95", 3)
    out += [
        "## Item 3: adaptive execution and volume-forecast errors (5% ADV, sqrt impact, cap 0.1; 20 seeds x 2000 paths)",
        "",
        markdown(
            a,
            [
                ("scenario", "scenario"),
                ("policy", "policy"),
                ("is", "IS bps"),
                ("vs_static", "vs static AC (bps)"),
                ("vs_vwap", "vs VWAP (bps)"),
                ("completion", "completion"),
            ],
            nd=3,
        ),
        "",
    ]
    s = read("solver_comparison.csv")
    for r in s:
        for k in ("max_err_exact", "max_err_ref_w", "max_err_ref_obj"):
            r[k] = f"{float(r[k]):.1e}"
        r["wall_ms_median"] = f"{float(r['wall_ms_median']):.2f}"
    with open(os.path.join(RES, "solvers_manifest.json"), encoding="utf-8") as fh:
        sm = json.load(fh)
    out += [
        "## Item 4: solver comparison (10 random problems per size; failures by the failure rule of the optimizers)",
        "",
        f"Solvers available: {', '.join(sm['solvers'])}; Gurobi: {'used' if sm.get('gurobi') else 'not importable in the project environment, skipped'}. "
        "Time: median over problems of the minimum of 3 solves on a shared machine.",
        "",
        markdown(
            s,
            [
                ("problem", "problem"),
                ("n", "n"),
                ("solver", "solver"),
                ("solves", "solves"),
                ("failed", "failed"),
                ("inaccurate", "inaccurate"),
                ("max_err_exact", "error vs closed form"),
                ("max_err_ref_w", "weights vs Clarabel 1e-10"),
                ("max_err_ref_obj", "objective vs Clarabel 1e-10"),
                ("wall_ms_median", "ms"),
            ],
            raw=(
                "n",
                "solves",
                "failed",
                "inaccurate",
                "max_err_exact",
                "max_err_ref_w",
                "max_err_ref_obj",
                "wall_ms_median",
            ),
        ),
        "",
    ]
    t = read("fat_tails.csv")
    for r in t:
        r["ce"] = pmx(r, "ce_ann_base_mean", "ce_ann_base_ci95")
        r["eff"] = pmx(r, "effect_of_shift_mean", "effect_of_shift_ci95")
        r["bmv"] = pmx(r, "base_diff_vs_MV", "base_diff_vs_MV_ci95")
        r["pmv"] = pmx(r, "post_shift_diff_vs_MV", "post_shift_diff_vs_MV_ci95")
    out += [
        "## Item 5: fat tails and jumps (assumed tail models; frozen S2 configurations; 30 seeds)",
        "",
        markdown(
            t,
            [
                ("tail_model", "tail model"),
                ("strategy", "strategy"),
                ("ce", "ce_ann (no shift)"),
                ("bmv", "vs MV (no shift)"),
                ("eff", "effect of the shift"),
                ("pmv", "vs MV after the shift"),
            ],
        ),
        "",
    ]
    c = read("cost_misspecification.csv")
    for r in c:
        r["ce"] = pmx(r, "ce_ann_mean", "ce_ann_ci95")
        r["loss"] = pmx(r, "loss_vs_parity", "loss_vs_parity_ci95") + (
            f" ({r['wtl']})" if r.get("wtl") else ""
        )
        r["capital"] = f"{float(r['capital']):g}"
        r["impact_y"] = f"{float(r['impact_y']):g}"
        r["belief"] = f"{float(r['belief']):g}"
    out += [
        "## Item 6: cost misspecification (tuned MV; the optimizer believes belief x the true costs; 20 seeds)",
        "",
        markdown(
            c,
            [
                ("impact_y", "impact y"),
                ("capital", "capital"),
                ("belief", "belief"),
                ("ce", "ce_ann"),
                ("loss", "vs parity (belief 1)"),
                ("turnover", "turnover/bar"),
            ],
            raw=("impact_y", "capital", "belief"),
        ),
        "",
    ]
    k = read("capacity.csv")
    for r in k:
        r["ce"] = pmx(r, "ce_ann_mean", "ce_ann_ci95")
        r["vs"] = pmx(r, "diff_vs_RANK_LS", "diff_vs_RANK_LS_ci95")
        r["capital"] = f"{float(r['capital']):g}"
    out += [
        "## Item 7: capacity (tuned MV and the naive RANK_LS; 20 seeds)",
        "",
        markdown(
            k,
            [
                ("strategy", "strategy"),
                ("capital", "capital"),
                ("ce", "ce_ann"),
                ("vs", "MV vs RANK_LS"),
                ("cap_binds_share", "cap binds (share of fills)"),
                ("cost_drag", "cost drag/yr"),
            ],
            raw=("capital",),
        ),
        "",
    ]
    with open(os.path.join(RES, "export_consumer.json"), encoding="utf-8") as fh:
        ex = json.load(fh)
    out += [
        "## Item 8: export consumer",
        "",
        f"An export of the `tiny` market (seed 5) written by this repository and read back through the consumer "
        f"(hashes, schemas, knowledge rule): a loop run on it gives logs identical to the run on the in-memory market: "
        f"{ex['identical_logs_in_memory_vs_export']}; the export's forecasts drive a rank strategy for "
        f"{ex['rank_export_decisions']} decisions (the market and seed are fixed in "
        f"`experiments/tier2_more.py`, `run_export`). No export of the research engine was available, "
        f"so that part was skipped.",
        "",
    ]
    with open(os.path.join("docs", "results_tier2.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
    print("docs/results_tier2.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
